language: node_js
node_js: stable
cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

branches:
  only:
    - release

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $CI_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build
  target_branch: gh-pages
  on:
    branch: release
   